name: Run save.py twice (history1 and history2)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # 12時間ごと（UTC基準）

jobs:
  history1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Loop save & upload for 6 hours (history1)
        run: |
          END_TIME=$((SECONDS + 21600))  # 6時間
          while [ $SECONDS -lt $END_TIME ]; do
            timestamp=$(date +'%Y%m%d_%H%M%S')

            # 保存処理
            python save.py history1

            # 圧縮
            tar -czf history1_$timestamp.tar.gz -C data/history1 .

            # 一時フォルダへ移動
            mv history1_$timestamp.tar.gz /tmp/

            # タイムスタンプを環境変数にセット
            echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV

            sleep 600
          done

      - uses: actions/upload-artifact@v3
        with:
          name: saved-pages-history1-${{ env.TIMESTAMP }}
          path: /tmp/history1_${{ env.TIMESTAMP }}.tar.gz

  history2:
    needs: history1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Loop save & upload for 6 hours (history2)
        run: |
          END_TIME=$((SECONDS + 21600))  # 6時間
          while [ $SECONDS -lt $END_TIME ]; do
            timestamp=$(date +'%Y%m%d_%H%M%S')

            # 保存処理
            python save.py history2

            # 圧縮
            tar -czf history2_$timestamp.tar.gz -C data/history2 .

            # 一時フォルダへ移動
            mv history2_$timestamp.tar.gz /tmp/

            # タイムスタンプを環境変数にセット
            echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV

            sleep 600
          done

      - uses: actions/upload-artifact@v3
        with:
          name: saved-pages-history2-${{ env.TIMESTAMP }}
          path: /tmp/history2_${{ env.TIMESTAMP }}.tar.gz
