name: Save history1 and history2 every 10 minutes

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # 10分ごと

jobs:
  save-history1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          python save.py history1
          echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: saved-pages-history1-${{ env.TIMESTAMP }}
          path: data/history1

  save-history2:
    needs: save-history1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          timestamp=$(date +'%Y%m%d_%H%M%S')
          python save.py history2
          echo "TIMESTAMP=$timestamp" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: saved-pages-history2-${{ env.TIMESTAMP }}
          path: data/history2
