name: Run save.py (manual or 6h schedule)

on:
  workflow_dispatch:         # 手動実行も可能
  schedule:
    - cron: "0 */6 * * *"     # 6時間ごとに自動実行（UTC基準）

jobs:
  run-python:
    runs-on: ubuntu-latest
    timeout-minutes: 360      # 最大6時間で終了（GitHub制限）

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python save.py
      - name: Upload saved HTML files
        uses: actions/upload-artifact@v4
        with:
          name: saved-pages
          path: data/
