name: Run save.py (manual or schedule)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # 10分ごと

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python save.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto save at $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
