name: Run save.py twice (history1 and history2)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # 12時間ごとに開始（UTC基準）

jobs:
  history1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Loop save for 6 hours (history1)
        run: |
          END_TIME=$((SECONDS + 21600))  # 6時間
          while [ $SECONDS -lt $END_TIME ]; do
            python save.py history1
            echo "Upload after each run..."
            zip -r history1.zip data/history1
            gh run upload-artifact "saved-pages-history1" history1.zip --overwrite
            sleep 600
          done
        env:
          GH_TOKEN: ${{ github.token }}

  history2:
    needs: history1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Loop save for 6 hours (history2)
        run: |
          END_TIME=$((SECONDS + 21600))  # 6時間
          while [ $SECONDS -lt $END_TIME ]; do
            python save.py history2
            echo "Upload after each run..."
            zip -r history2.zip data/history2
            gh run upload-artifact "saved-pages-history2" history2.zip --overwrite
            sleep 600
          done
        env:
          GH_TOKEN: ${{ github.token }}
