name: Run save.py twice (history1 and history2)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # 12時間ごと（UTC基準）

jobs:
  history1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y gh  # GitHub CLI

      - name: Loop save & upload for 6 hours (history1)
        run: |
          END_TIME=$((SECONDS + 21600))  # 6時間
          while [ $SECONDS -lt $END_TIME ]; do
            timestamp=$(date +'%Y%m%d_%H%M%S')

            # 保存処理
            python save.py history1

            # 圧縮
            tar -czf /tmp/history1_${timestamp}.tar.gz -C data/history1 .

            # アーティファクトを即時アップロード
            gh run upload-artifact "saved-pages-history1-${timestamp}" /tmp/history1_${timestamp}.tar.gz

            sleep 600  # 10分待機
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  history2:
    needs: history1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y gh  # GitHub CLI

      - name: Loop save & upload for 6 hours (history2)
        run: |
          END_TIME=$((SECONDS + 21600))  # 6時間
          while [ $SECONDS -lt $END_TIME ]; do
            timestamp=$(date +'%Y%m%d_%H%M%S')

            # 保存処理
            python save.py history2

            # 圧縮
            tar -czf /tmp/history2_${timestamp}.tar.gz -C data/history2 .

            # アーティファクトを即時アップロード
            gh run upload-artifact "saved-pages-history2-${timestamp}" /tmp/history2_${timestamp}.tar.gz

            sleep 600  # 10分待機
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
