name: Run save.py twice (history1 and history2)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # 12時間ごとに開始（UTC基準）

jobs:
  history1:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python save.py history1
      - name: Upload history1
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: saved-pages-history1
          path: data/history1/

  history2:
    needs: history1
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python save.py history2
      - name: Upload history2
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: saved-pages-history2
          path: data/history2/
