name: Fish Snapshot

on:
  schedule:
    - cron: "*/5 * * * *"  # 5分おき
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run snapshot script
        run: python save.py

      - name: Commit and push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto snapshot" || echo "No changes"
          git push
